# Generated by Django 4.2.7 on 2023-11-28 07:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='None', max_length=100)),
                ('last_name', models.CharField(default='None', max_length=100)),
                ('email', models.EmailField(default='test@gmail.com', max_length=254)),
                ('phone_number', models.CharField(default='None', max_length=15)),
                ('major_area_of_study', models.CharField(default='None', max_length=100)),
                ('year_in_program', models.PositiveIntegerField(default=1)),
                ('bio', models.TextField(default='None')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
